### ISSUE TITLE
New aimbot-2 is a little broken?

### ISSUE THREAD

**Issue by theHackor** [humphreygaming/surviv-cheat-source#10]
I tried two options, inverted aim and on shoot (autoaim option is way too obvious in game) and I don't know if it's just me but.. isn't it kinda broken? I mean it will like shoot so far to the left or right, instead of shooting at the enemy.. and sometimes it will aim correctly but then all of a sudden shoot in every direction or just flip my player as if I had the pan on (auto pan is disabled)

I used aimbot-2 before and it was way better than this, which confused me because the new update says that the aimbot is supposed to be even better than before. I opened this issue because I'd like to know if anyone else has this problem? Or is it just me?

And yea I know I can fix it myself, but I'm just curious if anyone else has an issue with the new aimbot.

**Comment by yeeter2003** [comment]
Play multiple games it will get better it trys to pre aim so that running Players get hit, switch block with no pan off too
ist working fine for me try playing like 10 games and then it schould work

**Comment by theHackor** [comment]
@yeeter2003 Interesting, I'll try it out. Thanks for commenting

**Comment by theHackor** [comment]
@yeeter2003 nah, it's predicting wrong 80% of the time, just tested it. It fails especially with the shotgun. Unless the distance between you and the player is close af, it does better then.

**Comment by yeeter2003** [comment]
im mostly not usin the shotty so its good for me...

**Comment by yeeter2003** [comment]
sometimes its just not shooting when the player could be shot and it does not show names

**Comment by anime120** [comment]
Hmm

**Comment by theHackor** [comment]
The aimbot-2.js didn't have any big changes, except the necessary ones after Vinnie changed the "obfuscate, scope" to "dataAccessor" and stuff so I'm thinking something may have went wrong there. Probably an easy fix, I'll look into later if no one else will.

**Comment by yeeter2003** [comment]
would be nice

**Comment by yeeter2003** [comment]
i had the Problem that it sometimes not detects the Player

**Comment by BestContributor402** [comment]
@theHackor the only thing I did notice when doing the refactor is I had to add a return located [here](https://github.com/humphreygaming/surviv-cheat-source/blob/e819b9c17de7c9a0065b0b8963247340b6bac4d8/src/cheat/plugins/aimbot-2.js#L215). It only gets hit when you first encounter someone. Besides that, I always use autoaim so I am curious if that makes a difference either.

**Comment by yeeter2003** [comment]
idk i just had the problem that i encoutered someone and it neither aimd at him nor started shooting anywhere

**Comment by theHackor** [comment]
I also now noticed that if you enable "aim at objects" it will remove all the esp and make the aa stop working. After disabling/enabling that option a few times, the aimbot and esp came back.

Anyways, here's what the issue with the aimbot looks like if you want to see exactly what I'm talking about @BestContributor402 : https://streamable.com/00mtfz

At first in the video you can see how the aimbot works properly when it doesn't have a weapon, and then for some reason when I switched to a gun, the aimbot is acting starnge. It moves in all types of directions, even though the player I was targetting wasn't moving. And it also stops shooting sometimes.

**Comment by BestContributor402** [comment]
@theHackor The "aim at objects" issue has been fixed in [this](https://github.com/humphreygaming/surviv-cheat-source/pull/11) PR. It was crashing the aimbot and the esp plugin causing them to stop working.

As far as the other issues with the aimbot, I'm not sure. I haven't had this happen to me. Make sure you are running surviv using [this](https://surviv.io/?dev&verbose) link. Check the console to see if any errors are popping up when aimbot acts weird.

**Comment by theHackor** [comment]
It still crashes for me and the consoel is catching no errors except a few about ads. 

Hey, do you mind sharing what changes needed to be done to fix the obfuscation patch? Just the necessary ones, without reconstucting the cheat. I still have the old source and I'm wondering if the aimbot would work properly again if I only implemented the small changes and kept the cheat's structure the way it was for the most part. Maybe that way I'll find what is causing the issue

**Comment by theHackor** [comment]
@BestContributor402 Can you compile this for me and send me the .zip : https://github.com/theHackor/surviv-cheat-old-structure

It's the structure before it was rewritten and I think I edited all the necessary stuff to fix the surviv patch. The new cheat structure unfortunaly breaks the aimbot for me and it just won't work no matter what browser I use etc. The reason why I would like you to compile it for me is because apparently the system I'm on right now has soem issues with nodejs and when compiling I get some EOF errors. (Not because of the cheat, its because of node_modules errors)
